CREATE TABLE IF NOT EXISTS server_joins (
    id INT AUTO_INCREMENT,
    player VARCHAR(50) NOT NULL,
    server VARCHAR(50) NOT NULL,
    ts DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE = INNODB;