CREATE TABLE IF NOT EXISTS whitelist (
    id INT AUTO_INCREMENT,
    player VARCHAR(50) NOT NULL UNIQUE,
    ip VARCHAR(50) NOT NULL UNIQUE,
    reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS blacklist (
    id INT AUTO_INCREMENT,
    player VARCHAR(50) NOT NULL UNIQUE,
    ip VARCHAR(50) NOT NULL UNIQUE,
    reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE = INNODB;